### ISSUE TITLE
Could you help me out please?

### ISSUE THREAD

**Issue by kevinchr** [rvegajr/image-ocr-renamer#1]
Hey,

I just installed node.js and the modules required for your app and when i try to run your app i see this error in log coming up {"level":"error","message":"ERROR: Error: Command failed: tesseract C:\\Users\\kevin\\AppData\\Local\\Temp\\image-ocr-renamer\\2016-01-09-23-01-56.jpg C:\\Users\\kevin\\AppData\\Local\\Temp\\node-tesseract-5fe392fe-4f1b-456a-a941-c42dace82f4b -l eng -psm 3\n'tesseract' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n","timestamp":"2018-04-26T17:09:41.958Z"}

And i have no idea how to fix it... 

Could you help me out please? :)

Thank you in advance 

And oh yeah my running system is windows 8.0 64bit

**Comment by rvegajr** [comment]
Hi! I am on my way to the airport, Let me check this out later this
evening.  If I don’t reach it to you by 10 central time.. spam me :)

**Comment by rvegajr** [comment]
So npm install doesn’t bring down the tesseract binaries. Do you know if
https://code.google.com/p/tesseract-ocr/downloads/detail?name=tesseract-ocr-setup-3.02.02.exe
was installed (they may have changed this site a bit, i will see if I can
download and and take a look later)

Cheers!

**Comment by kevinchr** [comment]
Hey, 

Thank you for the quick reply. I was able to install tesseract in the folder... But now i seem to get an error that async is deprecated so therefore the script aborts mission.

Thank you for having a look at it i would really like to try out your script :)

Cheers to you too

**Comment by rvegajr** [comment]
So I just checked in a version with updated node package I ran it and it looks like it is working. I am getting the following:
(node:12984) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
But the file is getting renamed.  do a pull and give it a go.

Thanks!

**Comment by johanndavel** [comment]
Hey man is this still working ?  Ive tried running it but i get

info: InputPath=C:\Program Files (x86)\Tesseract-OCR\data\input\
info: OutputPath=C:\Program Files (x86)\Tesseract-OCR\data\output\
info: ReprocessFiles=false
C:\Program Files (x86)\Tesseract-OCR\data\input\2016-01-09-23-01-56.jpg
fs.js:168
    throw new ERR_INVALID_CALLBACK(cb);
    ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefine
d
    at makeCallback (fs.js:168:11)
    at Object.unlink (fs.js:1199:14)
    at C:\Program Files (x86)\Tesseract-OCR\node_modules\node-tesseract\lib\tess
eract.js:99:14
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_c
ontext.js:63:3) {
  code: 'ERR_INVALID_CALLBACK

Im not sure what it meens. im running it in gitbash with the enviorment installed inside the tesseract-ocr folder in program files, its the only way ive gotten it to work up to this point
